export type SeoPageKey =
  | "home"
  | "login"
  | "signup"
  | "forgotPassword"
  | "resetPassword"
  | "privacy"
  | "terms"
  | "mentions"
  | "guideRegistration"
  | "guideSes"
  | "guideGuestRegister"
  | "guideAmsterdamNightCap"
  | "guideItalyCinAlloggiati"
  | "guidePortugalRnalSiba"
  | "guideGreeceAmaAade"
  | "guideCroatiaEvisitor"
  | "guideBelgiumStrRegistration"
  | "guideBelgiumStrRegistrationFr"
  | "guideBrusselsAirbnbRegistration"
  | "guideBrusselsAirbnbRegistrationFr"
  | "guideViennaStrRegistration"
  | "guideViennaStrRegistrationFr"
  | "guideViennaAirbnbRegistration"
  | "guideViennaAirbnbRegistrationFr"
  | "guideBerlinStrRegistration"
  | "guideBerlinStrRegistrationFr"
  | "guideBerlinAirbnbRegistration"
  | "guideBerlinAirbnbRegistrationFr"
  | "guideMunichStrRegistration"
  | "guideMunichStrRegistrationFr"
  | "guideMunichAirbnbRegistration"
  | "guideMunichAirbnbRegistrationFr"
  | "guideBarcelonaStrRegistration"
  | "guideBarcelonaStrRegistrationFr"
  | "guideBarcelonaAirbnbRegistration"
  | "guideBarcelonaAirbnbRegistrationFr"
  | "guideMadridStrRegistration"
  | "guideMadridStrRegistrationFr"
  | "guideMadridAirbnbRegistration"
  | "guideMadridAirbnbRegistrationFr"
  | "guideFrNerMigration";

export const PAGE_PATHS: Record<SeoPageKey, string> = {
  home: "",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  privacy: "/legal/privacy",
  terms: "/legal/terms",
  mentions: "/legal/mentions",
  guideRegistration: "/guides/numero-enregistrement-meuble",
  guideSes: "/guides/ses-hospedajes-espagne",
  guideGuestRegister: "/guides/fiche-police-voyageurs",
  guideAmsterdamNightCap: "/guides/amsterdam-night-cap",
  guideItalyCinAlloggiati: "/guides/italy-cin-alloggiati",
  guidePortugalRnalSiba: "/guides/rnal-siba-portugal",
  guideGreeceAmaAade: "/guides/greece-ama-aade",
  guideCroatiaEvisitor: "/guides/croatia-evisitor",
  guideBelgiumStrRegistration: "/guides/belgium-short-term-rental-registration",
  guideBelgiumStrRegistrationFr: "/guides/enregistrement-location-courte-duree-belgique",
  guideBrusselsAirbnbRegistration: "/guides/brussels-airbnb-registration",
  guideBrusselsAirbnbRegistrationFr: "/guides/enregistrement-airbnb-bruxelles",
  guideViennaStrRegistration: "/guides/vienna-short-term-rental-registration",
  guideViennaStrRegistrationFr: "/guides/enregistrement-location-courte-duree-vienne",
  guideViennaAirbnbRegistration: "/guides/vienna-airbnb-registration",
  guideViennaAirbnbRegistrationFr: "/guides/enregistrement-airbnb-vienne",
  guideBerlinStrRegistration: "/guides/berlin-short-term-rental-registration",
  guideBerlinStrRegistrationFr: "/guides/enregistrement-location-courte-duree-berlin",
  guideBerlinAirbnbRegistration: "/guides/berlin-airbnb-registration",
  guideBerlinAirbnbRegistrationFr: "/guides/enregistrement-airbnb-berlin",
  guideMunichStrRegistration: "/guides/munich-short-term-rental-registration",
  guideMunichStrRegistrationFr: "/guides/enregistrement-location-courte-duree-munich",
  guideMunichAirbnbRegistration: "/guides/munich-airbnb-registration",
  guideMunichAirbnbRegistrationFr: "/guides/enregistrement-airbnb-munich",
  guideBarcelonaStrRegistration: "/guides/barcelona-short-term-rental-registration",
  guideBarcelonaStrRegistrationFr: "/guides/enregistrement-location-courte-duree-barcelone",
  guideBarcelonaAirbnbRegistration: "/guides/barcelona-airbnb-registration",
  guideBarcelonaAirbnbRegistrationFr: "/guides/enregistrement-airbnb-barcelone",
  guideMadridStrRegistration: "/guides/madrid-short-term-rental-registration",
  guideMadridStrRegistrationFr: "/guides/enregistrement-location-courte-duree-madrid",
  guideMadridAirbnbRegistration: "/guides/madrid-airbnb-registration",
  guideMadridAirbnbRegistrationFr: "/guides/enregistrement-airbnb-madrid",
  guideFrNerMigration: "/guides/migration-ner-2026",
};
