export type SeoPageKey =
  | "guidesIndex"
  | "home"
  | "login"
  | "signup"
  | "forgotPassword"
  | "resetPassword"
  | "privacy"
  | "terms"
  | "mentions"
  | "guideRegistration"
  | "guideSes"
  | "guideGuestRegister"
  | "guideAmsterdamNightCap"
  | "guideAmsterdamStrRegistration"
  | "guideAmsterdamStrRegistrationFr"
  | "guideAmsterdamAirbnbRegistration"
  | "guideAmsterdamAirbnbRegistrationFr"
  | "guideItalyCinAlloggiati"
  | "guidePortugalRnalSiba"
  | "guideGreeceAmaAade"
  | "guideCroatiaEvisitor"
  | "guideBelgiumStrRegistration"
  | "guideBelgiumStrRegistrationFr"
  | "guideBrusselsAirbnbRegistration"
  | "guideBrusselsAirbnbRegistrationFr"
  | "guideViennaStrRegistration"
  | "guideViennaStrRegistrationFr"
  | "guideViennaAirbnbRegistration"
  | "guideViennaAirbnbRegistrationFr"
  | "guideBerlinStrRegistration"
  | "guideBerlinStrRegistrationFr"
  | "guideBerlinAirbnbRegistration"
  | "guideBerlinAirbnbRegistrationFr"
  | "guideMunichStrRegistration"
  | "guideMunichStrRegistrationFr"
  | "guideMunichAirbnbRegistration"
  | "guideMunichAirbnbRegistrationFr"
  | "guideBarcelonaStrRegistration"
  | "guideBarcelonaStrRegistrationFr"
  | "guideBarcelonaAirbnbRegistration"
  | "guideBarcelonaAirbnbRegistrationFr"
  | "guideMadridStrRegistration"
  | "guideMadridStrRegistrationFr"
  | "guideMadridAirbnbRegistration"
  | "guideMadridAirbnbRegistrationFr"
  | "guideValenciaStrRegistration"
  | "guideValenciaStrRegistrationFr"
  | "guideValenciaAirbnbRegistration"
  | "guideValenciaAirbnbRegistrationFr"
  | "guideMalagaStrRegistration"
  | "guideMalagaStrRegistrationFr"
  | "guideMalagaAirbnbRegistration"
  | "guideMalagaAirbnbRegistrationFr"
  | "guideSevilleStrRegistration"
  | "guideSevilleStrRegistrationFr"
  | "guideSevilleAirbnbRegistration"
  | "guideSevilleAirbnbRegistrationFr"
  | "guideFrNerMigration"
  | "guideIrelandStrRegistration"
  | "guideIrelandStrRegistrationFr"
  | "guideDublinAirbnbRegistration"
  | "guideDublinAirbnbRegistrationFr"
  | "guideParisStrRegistration"
  | "guideParisStrRegistrationFr"
  | "guideParisAirbnbRegistration"
  | "guideParisAirbnbRegistrationFr"
  | "guideLyonStrRegistration"
  | "guideLyonStrRegistrationFr"
  | "guideLyonAirbnbRegistration"
  | "guideLyonAirbnbRegistrationFr"
  | "guideMarseilleStrRegistration"
  | "guideMarseilleStrRegistrationFr"
  | "guideMarseilleAirbnbRegistration"
  | "guideMarseilleAirbnbRegistrationFr"
  | "guideBordeauxStrRegistration"
  | "guideBordeauxStrRegistrationFr"
  | "guideBordeauxAirbnbRegistration"
  | "guideBordeauxAirbnbRegistrationFr";

export const PAGE_PATHS: Record<SeoPageKey, string> = {
  guidesIndex: "/guides",
  home: "",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  privacy: "/legal/privacy",
  terms: "/legal/terms",
  mentions: "/legal/mentions",
  guideRegistration: "/guides/numero-enregistrement-meuble",
  guideSes: "/guides/ses-hospedajes-espagne",
  guideGuestRegister: "/guides/fiche-police-voyageurs",
  guideAmsterdamNightCap: "/guides/amsterdam-night-cap",
  guideAmsterdamStrRegistration: "/guides/amsterdam-short-term-rental-registration",
  guideAmsterdamStrRegistrationFr: "/guides/enregistrement-location-courte-duree-amsterdam",
  guideAmsterdamAirbnbRegistration: "/guides/amsterdam-airbnb-registration",
  guideAmsterdamAirbnbRegistrationFr: "/guides/enregistrement-airbnb-amsterdam",
  guideItalyCinAlloggiati: "/guides/italy-cin-alloggiati",
  guidePortugalRnalSiba: "/guides/rnal-siba-portugal",
  guideGreeceAmaAade: "/guides/greece-ama-aade",
  guideCroatiaEvisitor: "/guides/croatia-evisitor",
  guideBelgiumStrRegistration: "/guides/belgium-short-term-rental-registration",
  guideBelgiumStrRegistrationFr: "/guides/enregistrement-location-courte-duree-belgique",
  guideBrusselsAirbnbRegistration: "/guides/brussels-airbnb-registration",
  guideBrusselsAirbnbRegistrationFr: "/guides/enregistrement-airbnb-bruxelles",
  guideViennaStrRegistration: "/guides/vienna-short-term-rental-registration",
  guideViennaStrRegistrationFr: "/guides/enregistrement-location-courte-duree-vienne",
  guideViennaAirbnbRegistration: "/guides/vienna-airbnb-registration",
  guideViennaAirbnbRegistrationFr: "/guides/enregistrement-airbnb-vienne",
  guideBerlinStrRegistration: "/guides/berlin-short-term-rental-registration",
  guideBerlinStrRegistrationFr: "/guides/enregistrement-location-courte-duree-berlin",
  guideBerlinAirbnbRegistration: "/guides/berlin-airbnb-registration",
  guideBerlinAirbnbRegistrationFr: "/guides/enregistrement-airbnb-berlin",
  guideMunichStrRegistration: "/guides/munich-short-term-rental-registration",
  guideMunichStrRegistrationFr: "/guides/enregistrement-location-courte-duree-munich",
  guideMunichAirbnbRegistration: "/guides/munich-airbnb-registration",
  guideMunichAirbnbRegistrationFr: "/guides/enregistrement-airbnb-munich",
  guideBarcelonaStrRegistration: "/guides/barcelona-short-term-rental-registration",
  guideBarcelonaStrRegistrationFr: "/guides/enregistrement-location-courte-duree-barcelone",
  guideBarcelonaAirbnbRegistration: "/guides/barcelona-airbnb-registration",
  guideBarcelonaAirbnbRegistrationFr: "/guides/enregistrement-airbnb-barcelone",
  guideMadridStrRegistration: "/guides/madrid-short-term-rental-registration",
  guideMadridStrRegistrationFr: "/guides/enregistrement-location-courte-duree-madrid",
  guideMadridAirbnbRegistration: "/guides/madrid-airbnb-registration",
  guideMadridAirbnbRegistrationFr: "/guides/enregistrement-airbnb-madrid",
  guideValenciaStrRegistration: "/guides/valencia-short-term-rental-registration",
  guideValenciaStrRegistrationFr: "/guides/enregistrement-location-courte-duree-valence",
  guideValenciaAirbnbRegistration: "/guides/valencia-airbnb-registration",
  guideValenciaAirbnbRegistrationFr: "/guides/enregistrement-airbnb-valence",
  guideMalagaStrRegistration: "/guides/malaga-short-term-rental-registration",
  guideMalagaStrRegistrationFr: "/guides/enregistrement-location-courte-duree-malaga",
  guideMalagaAirbnbRegistration: "/guides/malaga-airbnb-registration",
  guideMalagaAirbnbRegistrationFr: "/guides/enregistrement-airbnb-malaga",
  guideSevilleStrRegistration: "/guides/seville-short-term-rental-registration",
  guideSevilleStrRegistrationFr: "/guides/enregistrement-location-courte-duree-seville",
  guideSevilleAirbnbRegistration: "/guides/seville-airbnb-registration",
  guideSevilleAirbnbRegistrationFr: "/guides/enregistrement-airbnb-seville",
  guideFrNerMigration: "/guides/migration-ner-2026",
  guideIrelandStrRegistration: "/guides/ireland-short-term-letting-register",
  guideIrelandStrRegistrationFr: "/guides/enregistrement-location-courte-duree-irlande",
  guideDublinAirbnbRegistration: "/guides/dublin-airbnb-registration",
  guideDublinAirbnbRegistrationFr: "/guides/enregistrement-airbnb-dublin",
  guideParisStrRegistration: "/guides/paris-short-term-rental-registration",
  guideParisStrRegistrationFr: "/guides/enregistrement-location-courte-duree-paris",
  guideParisAirbnbRegistration: "/guides/paris-airbnb-registration",
  guideParisAirbnbRegistrationFr: "/guides/enregistrement-airbnb-paris",
  guideLyonStrRegistration: "/guides/lyon-short-term-rental-registration",
  guideLyonStrRegistrationFr: "/guides/enregistrement-location-courte-duree-lyon",
  guideLyonAirbnbRegistration: "/guides/lyon-airbnb-registration",
  guideLyonAirbnbRegistrationFr: "/guides/enregistrement-airbnb-lyon",
  guideMarseilleStrRegistration: "/guides/marseille-short-term-rental-registration",
  guideMarseilleStrRegistrationFr:
    "/guides/enregistrement-location-courte-duree-marseille",
  guideMarseilleAirbnbRegistration: "/guides/marseille-airbnb-registration",
  guideMarseilleAirbnbRegistrationFr: "/guides/enregistrement-airbnb-marseille",
  guideBordeauxStrRegistration: "/guides/bordeaux-short-term-rental-registration",
  guideBordeauxStrRegistrationFr:
    "/guides/enregistrement-location-courte-duree-bordeaux",
  guideBordeauxAirbnbRegistration: "/guides/bordeaux-airbnb-registration",
  guideBordeauxAirbnbRegistrationFr: "/guides/enregistrement-airbnb-bordeaux",
};
