import { differenceInCalendarDays } from "date-fns";
import {
  BERLIN_OVERNIGHT_TAX_2026_PDF_URL,
  BERLIN_OVERNIGHT_TAX_FAQ_URL,
  USTG_SECTION_12_URL,
  USTG_SECTION_19_URL,
} from "./official-links";
import { FACTS_REVIEWED_AT } from "./monteur-kit-facts";

export const GUEST_STAY_TYPES = ["tourist", "business", "mid_term"] as const;
export type GuestStayType = (typeof GUEST_STAY_TYPES)[number];

export const DEFAULT_ACCOMMODATION_VAT_PERCENT = 7;
export const DEFAULT_EXTRAS_VAT_PERCENT = 19;
export const BERLIN_CITY_TAX_RATE_PERCENT = 7.5;
export const SMALL_BUSINESS_THRESHOLD_PREV_EUR = 25_000;
export const SMALL_BUSINESS_THRESHOLD_CURRENT_EUR = 100_000;

export type DeInvoicePack = {
  accommodationNetCents: number;
  extrasNetCents: number;
  accommodationVatRatePercent: number;
  extrasVatRatePercent: number;
  smallBusiness: boolean;
  cityTaxEnabled: boolean;
  notes?: string;
};

export function defaultInvoicePack(): DeInvoicePack {
  return {
    accommodationNetCents: 0,
    extrasNetCents: 0,
    accommodationVatRatePercent: DEFAULT_ACCOMMODATION_VAT_PERCENT,
    extrasVatRatePercent: DEFAULT_EXTRAS_VAT_PERCENT,
    smallBusiness: false,
    cityTaxEnabled: false,
  };
}

export function parseInvoicePackJson(raw: string | null | undefined): DeInvoicePack {
  if (!raw?.trim()) return defaultInvoicePack();
  try {
    const parsed = JSON.parse(raw) as Partial<DeInvoicePack>;
    return {
      ...defaultInvoicePack(),
      ...parsed,
      accommodationVatRatePercent:
        parsed.accommodationVatRatePercent ?? DEFAULT_ACCOMMODATION_VAT_PERCENT,
      extrasVatRatePercent: parsed.extrasVatRatePercent ?? DEFAULT_EXTRAS_VAT_PERCENT,
    };
  } catch {
    return defaultInvoicePack();
  }
}

export function countStayNights(checkIn: Date, checkOut: Date): number {
  return Math.max(0, differenceInCalendarDays(checkOut, checkIn));
}

function vatAmountCents(netCents: number, ratePercent: number): number {
  return Math.round((netCents * ratePercent) / 100);
}

export function buildStayConfirmationText(input: {
  locale: "en" | "fr";
  propertyName: string;
  propertyAddress: string;
  propertyCity: string;
  registrationNumber?: string | null;
  checkIn: Date;
  checkOut: Date;
  guestLabel?: string | null;
  companyName?: string | null;
  payer?: string | null;
  projectRef?: string | null;
}): string {
  const nights = countStayNights(input.checkIn, input.checkOut);
  const lines: string[] = [];
  const isFr = input.locale === "fr";

  lines.push(isFr ? "Confirmation de séjour (Aufenthaltsbestätigung)" : "Stay confirmation (Aufenthaltsbestätigung)");
  lines.push("");
  lines.push(
    isFr
      ? `Bien : ${input.propertyName}, ${input.propertyAddress}, ${input.propertyCity}`
      : `Property: ${input.propertyName}, ${input.propertyAddress}, ${input.propertyCity}`
  );
  if (input.registrationNumber?.trim()) {
    lines.push(
      isFr
        ? `Numéro d'enregistrement LCD : ${input.registrationNumber.trim()}`
        : `STR registration number: ${input.registrationNumber.trim()}`
    );
  }
  lines.push(
    isFr
      ? `Arrivée : ${input.checkIn.toISOString().slice(0, 10)}`
      : `Check-in: ${input.checkIn.toISOString().slice(0, 10)}`
  );
  lines.push(
    isFr
      ? `Départ : ${input.checkOut.toISOString().slice(0, 10)}`
      : `Check-out: ${input.checkOut.toISOString().slice(0, 10)}`
  );
  lines.push(isFr ? `Nuits : ${nights}` : `Nights: ${nights}`);
  if (input.guestLabel?.trim()) {
    lines.push(isFr ? `Invité : ${input.guestLabel.trim()}` : `Guest: ${input.guestLabel.trim()}`);
  }
  if (input.companyName?.trim()) {
    lines.push(isFr ? `Société : ${input.companyName.trim()}` : `Company: ${input.companyName.trim()}`);
  }
  if (input.payer?.trim()) {
    lines.push(isFr ? `Payeur : ${input.payer.trim()}` : `Payer: ${input.payer.trim()}`);
  }
  if (input.projectRef?.trim()) {
    lines.push(isFr ? `Réf. projet : ${input.projectRef.trim()}` : `Project ref: ${input.projectRef.trim()}`);
  }
  lines.push("");
  lines.push(
    isFr
      ? "Document généré par Glint Host Registry à titre de registre opérationnel. Ce n'est pas un conseil juridique ni une facture."
      : "Document generated by Glint Host Registry as an operational record. This is not legal advice or an invoice."
  );
  lines.push(
    isFr
      ? `Le règlement UE 2024/1028 couvre aussi les séjours d'affaires (source BNetzA, revu ${FACTS_REVIEWED_AT}).`
      : `EU Regulation 2024/1028 also covers business stays (BNetzA source, reviewed ${FACTS_REVIEWED_AT}).`
  );
  return lines.join("\n");
}

export function buildInvoicePackCsv(input: {
  stayId: string;
  propertyName: string;
  checkIn: Date;
  checkOut: Date;
  companyName?: string | null;
  projectRef?: string | null;
  pack: DeInvoicePack;
}): string {
  const nights = countStayNights(input.checkIn, input.checkOut);
  const accVat = vatAmountCents(
    input.pack.accommodationNetCents,
    input.pack.accommodationVatRatePercent
  );
  const extVat = vatAmountCents(input.pack.extrasNetCents, input.pack.extrasVatRatePercent);
  let cityTaxCents = 0;
  if (input.pack.cityTaxEnabled) {
    cityTaxCents = Math.round(
      (input.pack.accommodationNetCents * BERLIN_CITY_TAX_RATE_PERCENT) / 100
    );
  }

  const rows = [
    ["field", "value"],
    ["stay_id", input.stayId],
    ["property", input.propertyName],
    ["check_in", input.checkIn.toISOString().slice(0, 10)],
    ["check_out", input.checkOut.toISOString().slice(0, 10)],
    ["nights", String(nights)],
    ["company", input.companyName?.trim() ?? ""],
    ["project_ref", input.projectRef?.trim() ?? ""],
    ["accommodation_net_cents", String(input.pack.accommodationNetCents)],
    ["accommodation_vat_rate_percent", String(input.pack.accommodationVatRatePercent)],
    ["accommodation_vat_cents", String(accVat)],
    ["extras_net_cents", String(input.pack.extrasNetCents)],
    ["extras_vat_rate_percent", String(input.pack.extrasVatRatePercent)],
    ["extras_vat_cents", String(extVat)],
    ["small_business_flag", input.pack.smallBusiness ? "yes" : "no"],
    ["berlin_city_tax_enabled", input.pack.cityTaxEnabled ? "yes" : "no"],
    ["berlin_city_tax_cents", String(cityTaxCents)],
    ["ustg_12_url", USTG_SECTION_12_URL],
    ["ustg_19_url", USTG_SECTION_19_URL],
    ["berlin_tax_pdf_url", BERLIN_OVERNIGHT_TAX_2026_PDF_URL],
    ["berlin_tax_faq_url", BERLIN_OVERNIGHT_TAX_FAQ_URL],
    ["facts_reviewed_at", FACTS_REVIEWED_AT],
  ];

  return rows.map((row) => row.map(escapeCsvCell).join(",")).join("\n");
}

function escapeCsvCell(value: string): string {
  if (/[",\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function isBusinessStayType(stayType: string | null | undefined): boolean {
  return stayType === "business" || stayType === "mid_term";
}
